// ---------------------------------------------------------------------------
// GENERATED — a one-time snapshot (2026-09-24) of the grade-point tables that
// ar.qurtoba.net lists for 421 universities in 40 countries. Do not hand-edit;
// regenerate from the snapshot instead.
//
// UNVERIFIED: an independent, unofficial source. The tables it lists that we
// checked against official pages matched, except the University of Jordan
// (outdated — pre-Oct-2024 system). So a student whose university is detected
// from here is asked to confirm the table; our officially verified schemes in
// gradeSchemes.ts always take precedence over an entry here.
//
// A table is either letters + points (percentage cutoffs are NOT published and
// are estimated in gradeSchemes.ts) or, for percentage-average systems, bands
// of [lowest %, label].
// ---------------------------------------------------------------------------

export type CatalogTable = { l: string[]; p: number[] } | { pct: [number, string][] };

/** [slug, Arabic name, English name, country, index into CATALOG_TABLES] */
export type CatalogRow = [string, string, string, string, number];

export const CATALOG_TABLES: CatalogTable[] = [
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0]},
  {"l":["A","B+","B","C+","C","D+","D","F"],"p":[4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"pct":[[85,"ممتاز"],[75,"جيد جداً"],[65,"جيد"],[50,"مقبول"],[35,"ضعيف (راسب)"],[0,"ضعيف جداً (راسب)"]]},
  {"l":["A","AB","B","BC","C","D","E"],"p":[4,3.5,3,2.5,2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.75,3.5,3,2.75,2.5,2,1.75,1.5,1,0.75,0.5]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,1.75,1.5,0.75]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,1.75,1.5,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.75,3.5,3,2.5,2,1.5,1,0]},
  {"pct":[[89.5,"إمتياز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[44.5,"مقبول بقرار"],[0,"راسب"]]},
  {"pct":[[84,"ممتاز"],[76,"جيد جدا"],[68,"جيد"],[60,"مقبول"],[0,"راسب"]]},
  {"pct":[[90,"ممتاز"],[80,"جيد جداً"],[65,"جيد"],[50,"مقبول"],[35,"ضعيف (راسب)"],[0,"ضعيف جداً (راسب)"]]},
  {"pct":[[89.5,"إمتياز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[44.5,"راسب (قيد المراجعة)"],[0,"راسب"]]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[5,4.75,4.5,4,3.5,3,2.5,2,1]},
  {"pct":[[90,"استثنائي"],[80,"جيد جدا"],[70,"جيد"],[60,"متوسط"],[50,"مقبول"],[0,"راسب"]]},
  {"pct":[[84,"ممتاز"],[76,"جيد جدا"],[68,"جيد"],[60,"مقبول"],[50,"ضعيف"],[0,"راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.66,3.33,3,2.66,2.33,2,1.66,1.33,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.8,3.6,3.3,3,2.7,2.3,2,1.7,1.4,1.2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.7,3.5,3,2.7,2.5,2,1.7,1.3,1,0.7,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.75,3.5,3,2.75,2.5,2,1.75,1.3,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0]},
  {"pct":[[84,"ممتاز"],[76,"جيد جدا"],[68,"جيد"],[60,"مرضي"],[0,"راسب"]]},
  {"l":["A","B","C","D","F"],"p":[4,3,2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","H"],"p":[4,3.75,3.5,3,2.75,2.5,2,1.75,1.5,1,0.75,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.75,3.5,3,2.75,2.5,2,1.75,1.5,1,0.75,0]},
  {"l":["A+","A","B1","B2","B3","C1","C2","C3","F1","F2"],"p":[4,4,3.5,3.25,3,2.75,2.5,2,1.5,0]},
  {"pct":[[92,"ممتاز مع مرتبة الشرف"],[84,"ممتاز"],[76,"جيد جدًا"],[68,"جيّد"],[60,"مقبول"],[0,"راسب"]]},
  {"pct":[[92,"ممتاز مع مرتبة الشرف"],[84,"ممتاز"],[76,"جيد جداً"],[68,"جيد"],[60,"مقبول"],[0,"راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.83,3.66,3.33,3,2.66,2.33,2,1.66,1.33,1,0]},
  {"l":["A","B+","B","C+","C","D","F"],"p":[4,3.5,3,2.5,2,1.5,0]},
  {"l":["A","B","C","F"],"p":[4,3,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,3.75,3.25,3,2.75,2.25,2,1.75,1,0]},
  {"pct":[[85,"ممتاز"],[75,"جيد جداً"],[65,"جيد"],[60,"مقبول"],[35,"ضعيف (راسب)"],[0,"ضعيف جداً (راسب)"]]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["HD","D","C","P","N"],"p":[7,6,5,4,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,4,3.666,3.333,3,2.666,2.333,2,1.666,1.333,1,0]},
  {"l":["O","A+","A","B+","B","C+","C","D","F"],"p":[10,10,9,8,7,6,5,4,0]},
  {"l":["A","A-","B+","B","B-","C","D","E"],"p":[4,3.67,3.33,3,2.5,2,1,0]},
  {"l":["AA","BA","BB","CB","CC","DC","DD","FF"],"p":[4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.7,3.3,3,2.7,2.4,2.2,2,0]},
  {"l":["A","B+","B","C+","C","D+","D","F"],"p":[3.8,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[6,5.5,5,4.5,4,3.5,3,2.5,2,1.5,1,0.5,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","R"],"p":[4.33,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"pct":[[89.5,"ممتاز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[0,"راسب"]]},
  {"l":["S","A","B","C","D","E","F"],"p":[10,9,8,7,6,5,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","D-","F"],"p":[4.3,4,3.67,3.33,3,2.67,2.33,2,1.67,1,0.67,0]},
  {"l":["A+","A","B+","B","C+","C","D","F"],"p":[10,9,8,7,6,5,4,0]},
  {"l":["O","A+","A","B+","B","C","P","F"],"p":[4,3.6,3.2,2.8,2.4,2,1.6,0]},
  {"pct":[[89.5,"امتياز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[0,"راسب"]]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4.5,4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4.33,4,3.67,3.33,3,2.67,2.33,2,1.67,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","FM"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.7,3.4,3.2,3,2.8,2.6,2.4,2.2,2,1.5,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.7,3.5,3.3,3.2,3,2.9,2.8,2.6,2.3,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.7,3.5,3.2,3,2.7,2.5,2.3,2,1.7,0]},
  {"l":["A","B+","B","C+","C","F"],"p":[4,3.5,3,2.5,2,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,1,0]},
  {"l":[">=90","89","88","87","86","85","84","83","82","81","80","79","78","77","76","75","74","73","72","71","70","69","68","67","66","65","64","63","62","61","60"],"p":[4,3.93,3.86,3.78,3.7,3.63,3.54,3.46,3.38,3.29,3.2,3.11,3.02,2.92,2.82,2.73,2.62,2.52,2.42,2.31,2.2,2.09,1.98,1.86,1.74,1.63,1.5,1.38,1.26,1.13,1]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.8,3.5,3.2,2.9,2.6,2.3,2,1.7,1.4,1.2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","D-","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","E"],"p":[4,3.75,3.25,3,2.75,2.25,2,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D","E"],"p":[4.33,4,3.67,3.33,3,2.67,2.33,2,1,0]},
  {"l":["AA","BA","BB","CB","CC","DC","DD","FD","FF"],"p":[4,3.5,3,2.5,2,1.5,1,0.5,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.5,1,0]},
  {"pct":[[84,"ممتاز"],[76,"جيد جدًا"],[68,"جيّد"],[60,"مقبول"],[0,"راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[5,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7]},
  {"l":["A1","A2","B1","B2","C1","C2","D1","D2","F3"],"p":[4,3.5,3,2.5,2,1.5,1,0.5,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","E"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["A","B","C","D","E","F"],"p":[4,3.5,3,2.5,2,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A+","A","B+","B","C+","C","C-","D","F"],"p":[4,3.7,3.3,3,2.3,2,1.3,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.5,1,0]},
  {"l":["A+","B+","A","B","B-","A-","C","D","E"],"p":[4.3,3.3,3,3,2.7,2.7,2,1,0]},
  {"pct":[[90,"ممتاز"],[80,"جيد جدًا"],[70,"جيد"],[60,"حسن"],[50,"مقبول"],[0,"راسب"]]},
  {"l":["AA","BA","BB","CB","CC","DD","FF","FD"],"p":[4,3.5,3,2.5,2,1.5,1,0]},
  {"pct":[[84,"ممتاز"],[76,"جيد جدا"],[68,"جيد"],[60,"مقبول"],[0,"ضعيف"]]},
  {"pct":[[90,"متميز"],[85,"ممتاز"],[80,"جيد جدًا"],[75,"جيد"],[70,"متوسط"],[60,"مقبول"],[0,"راسب"]]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.5,3.33,3,2.5,2.33,2,1.5,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4.2,4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,1.75,1.5,0.5]},
  {"l":["O","A+","A","B+","B","C","P","R"],"p":[10,9,8,7,6,5,4,0]},
  {"l":["O","A+","A","B+","B","C","P","F"],"p":[10,9,8,7,6,5,4,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","E"],"p":[5,4.75,4.5,4,3.5,3,2.5,2,1]},
  {"pct":[[89.5,"ممتاز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"كاف"],[49.5,"مقبول"],[0,"ضعيف / فاشل"]]},
  {"l":["A+","Ao","A-","B+","Bo","B-","C+","Co","C-","D+","Do","D-","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.33,1,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.8,3.5,3,2.5,2,1.5,1,0]},
  {"l":[">=90","89","88","87","86","85","84","83","82","81","80","79","78","77","76","75","74","73","72","71","70","69","68","67","66","65","64","63","62","61","60"],"p":[4,3.9,3.8,3.7,3.6,3.5,3.4,3.3,3.2,3.1,3,2.9,2.8,2.7,2.6,2.5,2.4,2.3,2.2,2.1,2,1.9,1.8,1.7,1.6,1.5,1.4,1.3,1.2,1.1,1]},
  {"l":["A+","A","B+","B","C+","C","D+","D","E","F"],"p":[5,4.5,4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A","B","C","D","F"],"p":[5,4,3,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.8,1.5,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.9,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,1.75,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.8,3.6,3.4,3.2,3,2.8,2.6,2.4,2.2,2,0]},
  {"l":["HD","D","C","P","N"],"p":[4,3,2,1,0]},
  {"pct":[[84,"ممتاز"],[76,"جيّد جدًا"],[68,"جيّد"],[60,"مقبول"],[0,"راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D+","D","F"],"p":[5,5,4.5,4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,0]},
  {"l":["A+","A","B+","B","C+","C","D","F"],"p":[4,3.666,3.333,3,2.666,2.333,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.667,3.333,3,2.667,2.333,2,1.667,1.333,1,0]},
  {"l":["A","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[5,4.5,4,3.5,3,2.5,2,1.5,1,0.5,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","E"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1,0]},
  {"l":["A+","A","A-","B+","B","C+","C","C-","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1,0]},
  {"l":["O","A","B","C","D","E","F"],"p":[10,9,8,7,6,5,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","E"],"p":[4,3.67,3.33,3,2.67,2.33,2,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1,0]},
  {"l":["A+","A","B+","B","C+","C","C-","D+","D","F"],"p":[4,3.85,3.75,3.4,3,2.7,2.35,1.85,1.25,0]},
  {"l":["A+","A","B+","B","C+","C","F"],"p":[4,3.75,3.5,3,2.5,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","F"],"p":[4,3.7,3.5,3.2,2.9,2.6,2.3,2,0]},
  {"l":["A+","A0","A-","B+","B0","B-","C+","C0","C-","D+","D0","D-","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D+","F"],"p":[5.3,5,4.5,4,3.5,3,2.5,2,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[5,4.5,4,3.5,3,2.5,2,1.2,1,0.5,0]},
  {"l":["O+","O","A+","A","B+","B","C","P","F"],"p":[10,9,8,7,6,5.5,5,4,0]},
  {"l":["A+","A","B+","B","C+","C","D","F"],"p":[4,3.667,3.333,3,2.667,2.333,2,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","PC","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1,0.5,0]},
  {"pct":[[84,"ممتاز"],[76,"جيد جداً"],[68,"جيد"],[60,"مقبول"],[0,"ضعيف / راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4.01,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["A","A-","B+","B","B-","C+","C","F"],"p":[4,3.66,3.33,3,2.66,2.33,2,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4.33,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"pct":[[89.5,"امتياز"],[79.5,"جيد جداً"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[44.5,"مقبول بقرار"],[0,"راسب"]]},
  {"l":["AA","A","B","C","D"],"p":[4,3,2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","E"],"p":[4,3.75,3.5,3,2.75,2.5,2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","E"],"p":[4,3.66,3.33,3,2.66,2.33,2,1,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","P","F"],"p":[5,4.5,4,3.5,3,2.5,2,1.5,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","D","D-","E","F"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.75,3.5,3,2.75,2.5,2,1.75,1.5,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","E"],"p":[4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","E"],"p":[4,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","E","F"],"p":[4,4,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0.67,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D+","D"],"p":[9,8,7,6,5,4,3,2,1,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F+","F","F-"],"p":[4.25,4,3.75,3.5,3.25,3,2.75,2.5,2.25,2,1.5,1,0.75,0.5,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","R","D"],"p":[9,8,7,6,5,4,3,2,1,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,3.6667,3.3333,3,2.6667,2.3333,2,1.6667,1.3333,1,0.6667,0]},
  {"l":["O","A+","A","B+","B","C","D","F"],"p":[10,9,8,7,6,5,4,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D","F"],"p":[4,4,3.67,3.33,3,2.67,2.33,2,1.67,1,0]},
  {"pct":[[89.5,"إمتياز"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[44.5,"راسب (قيد المراجعة)"],[0,"راسب"]]},
  {"pct":[[89.5,"إمتياز"],[79.5,"جيد جدًَا"],[69.5,"جيد"],[59.5,"متوسط"],[49.5,"مقبول"],[0,"راسب"]]},
  {"pct":[[90,"امتياز"],[80,"جيد جداً"],[70,"جيد"],[60,"متوسط"],[50,"مقبول"],[45,"راسب (قيد المعالجة)"],[0,"راسب"]]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","E"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","E","F"],"p":[4.3,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.5,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","C-","D+","D","F"],"p":[4,3.89,3.67,3.33,3,2.67,2.33,2,1.67,1.33,1,0]},
  {"l":["HD","D","CR","PS","MF","FL","WF","FA"],"p":[7,6,5,4,3,1.5,1.5,1]},
  {"pct":[[90,"استثنائي"],[80,"ممتاز"],[65,"جيد"],[50,"مقبول"],[0,"راسب"]]},
  {"l":["A","A+","A-","B+","B","B-","C+","C","C-","D+","D","D-","F"],"p":[4,4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,0.7,0]},
  {"l":["A+","A","A-","B+","B","B-","C+","C","D","F"],"p":[9,8,7,6,5,4,3,2,1,0]},
  {"l":["HD","D","CR","P","N"],"p":[7,6,5,4,0]},
  {"l":["A","AB","B","BC","C","D","F"],"p":[4,3.5,3,2.5,2,1,0]},
  {"l":["O","S","A","B","C","F"],"p":[10,9,8,7,6,0]},
  {"l":["A+","A","B+","B","C+","C","D+","D","E","F"],"p":[9,8,7,6,5,4,3,2,1,0]},
  {"l":["A","A-","B+","B","B-","C+","C","C-","F"],"p":[4,3.6667,3.3333,3,2.6667,2.3333,2,1.6667,0]},
];

export const CATALOG: CatalogRow[] = [
  ["abu-dhabi-polytechnic","أبوظبي بوليتكنك","Abu Dhabi Polytechnic","United Arab Emirates",0],
  ["abu-dhabi-university","جامعة أبوظبي","Abu Dhabi University","United Arab Emirates",1],
  ["academic-bridge-programme","برنامج الجسر الأكاديمي","Academic Bridge Programme","Qatar",2],
  ["ada-university","الجامعة الأكاديمية الدبلوماسية الأذربيجانية","ADA University","Azerbaijan",3],
  ["africa-university-for-humanitarian-and-applied-sciences","جامعة أفريقيا للعلوم الإنسانية والتطبيقية","Africa University for Humanitarian and Applied Sciences","Libya",4],
  ["ahlia-university","الجامعة الأهلية","Ahlia University","Bahrain",3],
  ["ain-shams-university","جامعة عين شمس","Ain Shams University","Egypt",0],
  ["airlangga-university","جامعة ايرلانجا","Airlangga University","Indonesia",5],
  ["ajman-university","جامعة عجمان","Ajman University","United Arab Emirates",1],
  ["al-ahliyya-amman-university","جامعة عمّان الأهلية","Al-Ahliyya Amman University","Jordan",6],
  ["al-ain-university","جامعة العين","Al Ain University","United Arab Emirates",1],
  ["al-akhawayn-university","جامعة الأخوين","Al Akhawayn University","Morocco",7],
  ["al-al-bayt-university","جامعة آل البيت","Al al-Bayt University","Jordan",8],
  ["al-andalus-university-for-medical-sciences","جامعة الأندلس الخاصة للعلوم الطبية","Al-Andalus University for Medical Sciences","Syria",9],
  ["al-baha-university","جامعة الباحة","Al Baha University","Saudi Arabia",10],
  ["al-balqa-applied-university","جامعة البلقاء التطبيقية","Al-Balqa Applied University","Jordan",6],
  ["al-buraimi-university-college","كلية البريمي الجامعية","Al Buraimi University College","Oman",0],
  ["al-dar-university-college","كلية الدار الجامعية","Al Dar University College","United Arab Emirates",1],
  ["al-falah-university","جامعة الفلاح","Al Falah University","United Arab Emirates",1],
  ["al-furat-al-awsat-technical-university","جامعة الفرات الأوسط التقنية","Al-Furat Al-Awsat Technical University","Iraq",11],
  ["al-ghurair-university","جامعة الغرير","Al Ghurair University","United Arab Emirates",0],
  ["al-hadba-university","جامعة الحدباء","Al-Hadba University","Iraq",11],
  ["al-hussein-bin-talal-university","جامعة الحسين بن طلال","Al-Hussein Bin Talal University","Jordan",12],
  ["al-imam-al-ouzai-university","جامعة الإمام الأوزعي","Al Imam Al Ouzai University","Lebanon",13],
  ["al-imam-mohammad-ibn-saud-islamic-university","جامعة الإمام محمد بن سعود الإسلامية","Al Imam Mohammad Ibn Saud Islamic University","Saudi Arabia",10],
  ["al-iraqia-university","الجامعة العراقية","Al-Iraqia University","Iraq",14],
  ["al-jawf-university","جامعة الجوف","Al Jawf University","Saudi Arabia",15],
  ["al-jufra-university","جامعة الجفرة","Al-Jufra University","Libya",4],
  ["al-khawarizmi-international-college","كلية الخوارزمي الدولية","Al Khawarizmi International College","United Arab Emirates",1],
  ["al-maaref-university","جامعة المعارف","Al Maaref University","Lebanon",1],
  ["al-mansour-university-college","كلية المنصور الجامعة","Al-Mansour University College","Iraq",11],
  ["al-mawakeb-university","جامعة المواكب","Al-Mawakeb University","Libya",4],
  ["al-muthanna-university","جامعة المثنى","Al-Muthanna University","Iraq",14],
  ["al-qasim-green-university","جامعة القاسم الخضراء","Al-Qasim Green University","Iraq",11],
  ["al-qasimia-university","الجامعة القاسمية","Al Qasimia University","United Arab Emirates",1],
  ["al-sham-private-university","جامعة الشام الخاصة","Al-Sham Private University","Syria",9],
  ["al-sharqiyah-university","جامعة الشرقية","Al-Sharqiyah University","Oman",0],
  ["al-turath-university-college","جامعة التراث","Al Turath University College","Iraq",16],
  ["al-wasl-university","جامعة الوصل","Al Wasl University","United Arab Emirates",1],
  ["al-zaytoonah-university-of-jordan","جامعة الزيتونة الأردنية","Al-Zaytoonah University of Jordan","Jordan",17],
  ["alamein-international-university","جامعة العلمين الدولية","Alamein International University","Egypt",18],
  ["alasmarya-islamic-university","الجامعة الأسمرية الإسلامية","Alasmarya Islamic University","Libya",4],
  ["alexandria-university","جامعة الإسكندرية","Alexandria University","Egypt",19],
  ["alfaisal-university","جامعة الفيصل","Alfaisal University","Saudi Arabia",10],
  ["algonquin-college-in-kuwait","كلية الجونكوين الكندية في الكويت","Algonquin College in Kuwait","Kuwait",20],
  ["aljafara-university","جامعة الجفارة","Aljafara University","Libya",4],
  ["almaarefa-university","جامعة المعرفة","AlMaarefa University","Saudi Arabia",10],
  ["american-college-of-dubai","الكلية الأمريكية في دبي","American College of Dubai","United Arab Emirates",1],
  ["american-college-of-the-middle-east","كلية الشرق الأوسط الأمريكية","American College of the Middle East","Kuwait",2],
  ["american-international-university-aiu","الجامعة الأمريكية الدولية","American International University (AIU)","Kuwait",21],
  ["american-university-in-dubai","الجامعة الأمريكية في دبي","American University in Dubai","United Arab Emirates",0],
  ["american-university-in-the-emirates","الجامعة الأمريكية في الإمارات","American University in The Emirates","United Arab Emirates",1],
  ["american-university-of-armenia","الجامعة الأمريكية في أرمينيا","American University of Armenia","Armenia",22],
  ["american-university-of-bahrain","الجامعة الأمريكية بالبحرين","American University of Bahrain","Bahrain",23],
  ["american-university-of-beirut","الجامعة الأمريكية في بيروت","American University of Beirut","Lebanon",24],
  ["american-university-of-culture-and-education","الجامعة الأمريكية للثقافة والتعليم","American University of Culture and Education","Lebanon",1],
  ["american-university-of-iraq-sulaimani","الجامعة الأمريكية في العراق، السليمانية","American University of Iraq, Sulaimani","Iraq",0],
  ["american-university-of-kuwait","الجامعة الأمريكية في الكويت","American University of Kuwait","Kuwait",2],
  ["american-university-of-madaba-aum","الجامعة الأمريكية في مادبا","American University of Madaba (AUM)","Jordan",25],
  ["american-university-of-ras-al-khaimah","الجامعة الأمريكية في رأس الخيمة","American University of Ras Al Khaimah","United Arab Emirates",0],
  ["american-university-of-science-and-technology","الجامعة الأمريكية للعلوم والتكنولوجيا","American University of Science and Technology","Lebanon",26],
  ["american-university-of-sharjah","الجامعة الأمريكية في الشارقة","American University of Sharjah","United Arab Emirates",0],
  ["american-university-of-technology","الجامعة الأمريكية للتكنولوجيا","American University of Technology","Lebanon",1],
  ["amman-arab-university","جامعة عمّان العربية","Amman Arab University","Jordan",27],
  ["an-najah-national-university","جامعة النجاح الوطنية","An-Najah National University","Palestine",28],
  ["ankara-university","جامعة أنقرة","Ankara University","Turkey",29],
  ["antioch-syrian-private-university","جامعة أنطاكيه السورية الخاصة","Antioch Syrian Private University","Syria",9],
  ["antonine-university","الجامعة الأنطونية","Antonine University","Lebanon",18],
  ["applied-science-private-university","جامعة العلوم التطبيقية الخاصة","Applied Science Private University","Jordan",30],
  ["applied-science-university","جامعة العلوم التطبيقية","Applied Science University","Bahrain",31],
  ["arab-academy-for-science-technology-and-maritime-transport","الأكاديمية العربية للعلوم والتكنولوجيا والنقل البحري","Arab Academy for Science, Technology and Maritime Transport","Egypt",32],
  ["arab-international-university","الجامعة العربية الدولية","Arab International University","Syria",9],
  ["arab-open-university","الجامعة العربية المفتوحة","Arab Open University","Jordan",33],
  ["arab-private-university-for-science-and-technology","الجامعة العربية الخاصة للعلوم والتكنولوجيا","Arab Private University for Science and Technology","Syria",9],
  ["arabian-gulf-university","جامعة الخليج العربي","Arabian Gulf University","Bahrain",3],
  ["arkansas-state-university-in-qatar","جامعة ولاية أركنساس في قطر","Arkansas State University in Qatar","Qatar",34],
  ["assiut-university","جامعة أسيوط","Assiut University","Egypt",0],
  ["assumption-university-of-thailand","جامعة الافتراض في تايلاند","Assumption University of Thailand","Thailand",35],
  ["aswan-university","جامعة أسوان","Aswan University","Egypt",1],
  ["attahadi-university","جامعة التحدي","Attahadi University","Libya",36],
  ["augsburg-university","جامعة أوغسبورغ","Augsburg University","Germany",37],
  ["australian-college-of-kuwait","الكلية الأسترالية في الكويت","Australian College of Kuwait","Kuwait",3],
  ["australian-national-university","الجامعة الوطنية الأسترالية","Australian National University","Australia",38],
  ["badr-university-in-cairo","جامعة بدر بالقاهرة","Badr University in Cairo","Egypt",18],
  ["baghdad-college-of-medical-sciences","كلية بغداد للعلوم الطبية","Baghdad College of Medical Sciences","Iraq",14],
  ["bahrain-polytechnic","بوليتكنك البحرين","Bahrain Polytechnic","Bahrain",39],
  ["bandung-institute-of-technology-itb","معهد باندونغ للتكنولوجيا","Bandung Institute of Technology (ITB)","Indonesia",5],
  ["bard-college-berlin","كلية بارد في برلين","Bard College Berlin","Germany",40],
  ["beirut-arab-university","جامعة بيروت العربية","Beirut Arab University","Lebanon",0],
  ["benghazi-modern-university","جامعة بنغازي الحديثة","Benghazi Modern University","Libya",1],
  ["benha-national-university","جامعة بنها الأهلية","Benha National University","Egypt",0],
  ["benha-university","جامعة بنها","Benha University","Egypt",41],
  ["beni-suef-university","جامعة بني سويف","Beni-Suef University","Egypt",0],
  ["bennett-university","جامعة بينيت","Bennett University","India",42],
  ["bilkent-university","جامعة بيلكنت","Bilkent University","Turkey",18],
  ["bina-nusantara-university-binus","جامعة بينا نوسانتارا","Bina Nusantara University (BINUS)","Indonesia",43],
  ["bogazici-university","جامعة بوغازجي","Boğaziçi University","Turkey",44],
  ["bogor-agricultural-university","جامعة بوغور الزراعية","Bogor Agricultural University","Indonesia",5],
  ["brown-university","جامعة براون","Brown University","United States",0],
  ["cairo-university","جامعة القاهرة","Cairo University","Egypt",45],
  ["canadian-university-dubai","الجامعة الكندية في دبي","Canadian University Dubai","United Arab Emirates",46],
  ["capital-university","جامعة العاصمة","Capital University","United States",3],
  ["carleton-university","جامعة كارلتون","Carleton University","Canada",47],
  ["carnegie-mellon-university","جامعة كارنيغي ميلون","Carnegie Mellon University","United States",48],
  ["carnegie-mellon-university-in-qatar","جامعة كارنيجي ميلون في قطر","Carnegie Mellon University in Qatar","Qatar",48],
  ["catholic-university-in-erbil","الجامعة الكاثوليكية في أربيل","Catholic University in Erbil","Iraq",49],
  ["central-university-of-kerala","الجامعة المركزية في ولاية كيرالا","Central University of Kerala","India",50],
  ["cept-university","جامعة مركز التخطيط البيئي والتكنولوجيا","CEPT University","India",51],
  ["chandigarh-university","جامعة شانديغار","Chandigarh University","India",52],
  ["chiang-mai-university","جامعة شيانغ ماي","Chiang Mai University","Thailand",1],
  ["chinese-university-of-hong-kong","الجامعة الصينية في هونغ كونغ","Chinese University of Hong Kong","Hong Kong",0],
  ["christ-university","جامعة كريست","CHRIST University","India",53],
  ["cihan-university","جامعة جيهان","Cihan University","Iraq",54],
  ["city-university-al-manar-university","جامعة المدينة (جامعة المنار)","City University (Al Manar University)","Lebanon",55],
  ["city-university-college-of-ajman","كلية المدينة الجامعية عجمان","City University College of Ajman","United Arab Emirates",1],
  ["city-university-of-hong-kong","جامعة مدينة هونغ كونغ","City University of Hong Kong","Hong Kong",56],
  ["columbia-university","جامعة كولومبيا","Columbia University","United States",57],
  ["community-college-of-qatar","كلية المجتمع في قطر","Community College of Qatar","Qatar",1],
  ["concordia-university","جامعة كونكورديا","Concordia University","Canada",58],
  ["cornell-university","جامعة كورنيل","Cornell University","United States",58],
  ["daffodil-international-university","جامعة دافوديل الدولية","Daffodil International University","Bangladesh",59],
  ["daha-international-university","جامعة طه العالمية","Daha International University","Somalia",60],
  ["dalhousie-university","جامعة دالهاوسي","Dalhousie University","Canada",61],
  ["damanhour-university","جامعة دمنهور","Damanhour University","Egypt",62],
  ["damietta-university","جامعة دمياط","Damietta University","Egypt",63],
  ["dar-al-hekma-university","جامعة دار الحكمة","Dar Al-Hekma University","Saudi Arabia",15],
  ["dar-al-uloom-university","جامعة دار العلوم","Dar Al Uloom University","Saudi Arabia",10],
  ["delta-university-for-science-and-technology","جامعة دلتا للعلوم والتكنولوجيا","Delta University for Science and Technology","Egypt",2],
  ["denmark-technical-college","الكلية التقنية الدنماركية","Denmark Technical College","Denmark",26],
  ["deraya-university","جامعة دراية","Deraya University","Egypt",64],
  ["dhofar-university","جامعة ظفار","Dhofar University","Oman",0],
  ["diponegoro-university","جامعة ديبونيغورو","Diponegoro University","Indonesia",5],
  ["doha-institute-for-graduate-studies","معهد الدوحة للدراسات العيا","Doha Institute for Graduate Studies","Qatar",65],
  ["duke-university","جامعة ديوك","Duke University","United States",66],
  ["east-international-university-azm-university","جامعة الشرق الدولية (جامعة العزم)","East International University (Azm University)","Lebanon",67],
  ["eastern-mediterranean-university","جامعة شرق البحر المتوسط","Eastern Mediterranean University","Turkey",2],
  ["egypt-japan-university-of-science-and-technology","الجامعة المصرية اليابانية للعلوم والتكنولوجيا","Egypt-Japan University of Science and Technology","Egypt",0],
  ["egyptian-russian-university","الجامعة المصرية الروسية","Egyptian Russian University","Egypt",68],
  ["emirates-aviation-university","جامعة الإمارات للطيران","Emirates Aviation University","United Arab Emirates",1],
  ["emirates-canadian-university-college","الكلية الإماراتية الكندية الجامعية","Emirates Canadian University College","United Arab Emirates",0],
  ["emirates-college-for-management-and-information-technology","كلية الإمارات للإدارة وتكنولوجيا المعلومات","Emirates College for Management and Information Technology","United Arab Emirates",1],
  ["emirates-diplomatic-academy","أكاديمية الإمارات الدبلوماسية","Emirates Diplomatic Academy","United Arab Emirates",0],
  ["european-university-college","الكلية الأوروبية الجامعية","European University College","United Arab Emirates",1],
  ["fahd-bin-sultan-university","جامعة فهد بن سلطان","Fahd bin Sultan University","Saudi Arabia",15],
  ["fakeeh-college-for-medical-sciences","كلية فقيه للعلوم الطبية","Fakeeh College for Medical Sciences","Saudi Arabia",15],
  ["fatima-college-of-health-sciences","كلية فاطمة للعلوم الصحية","Fatima College of Health Sciences","United Arab Emirates",0],
  ["fayoum-university","جامعة الفيوم","Fayoum University","Egypt",18],
  ["fudan-university","جامعة فودان","Fudan University","China",69],
  ["future-university-in-egypt","جامعة المستقبل - مصر","Future University in Egypt","Egypt",0],
  ["gadjah-mada-university","جامعة غاجاه مادا","Gadjah Mada University","Indonesia",70],
  ["galala-university","جامعة الجلالة","Galala University","Egypt",71],
  ["gazi-university","جامعة غازي","Gazi University","Turkey",72],
  ["georgetown-university-school-of-foreign-service-in-qatar","جامعة جورجتاون في قطر","Georgetown University School of Foreign Service in Qatar","Qatar",3],
  ["georgia-institute-of-technology","معهد جورجيا للتكنولوجيا","Georgia Institute of Technology","United States",26],
  ["georgia-state-university","جامعة ولاية جورجيا","Georgia State University","Georgia",56],
  ["georgian-court-university","جامعة جورجيان كورت","Georgian Court University","Georgia",73],
  ["german-jordanian-university-gju","الجامعة الأردنية الألمانية","German Jordanian University (GJU)","Jordan",74],
  ["german-university-in-cairo","الجامعة الألمانية في القاهرة","German University in Cairo","Egypt",75],
  ["gulf-medical-university","جامعة الخليج الطبية","Gulf Medical University","United Arab Emirates",1],
  ["gulf-university","الجامعة الخليجية","Gulf University","Bahrain",3],
  ["gulf-university-for-science-and-technology","جامعة الخليج للعلوم والتكنولوجيا","Gulf University for Science and Technology","Kuwait",0],
  ["hacettepe-university","جامعة حجة تبة","Hacettepe University","Turkey",76],
  ["hamad-bin-khalifa-university","جامعة حمد بن خليفة","Hamad bin Khalifa University","Qatar",37],
  ["hamdan-bin-mohammed-smart-university","جامعة حمدان بن محمد الذكية","Hamdan Bin Mohammed Smart University","United Arab Emirates",1],
  ["harvard-university","جامعة هارفرد","Harvard University","United States",77],
  ["hec-paris-in-qatar","مدرسة الدراسات العليا التجارية في باريس - قطر","HEC Paris in Qatar","Qatar",78],
  ["heliopolis-university","جامعة هليوبوليس","Heliopolis University","Egypt",2],
  ["helwan-university","جامعة حلوان","Helwan University","Egypt",18],
  ["higher-colleges-of-technology","كليات التقنية العليا","Higher Colleges of Technology","United Arab Emirates",0],
  ["holy-family-university","جامعة العائلة المقدّسة","Holy Family University","Lebanon",24],
  ["holy-spirit-university-of-kaslik","جامعة الروح القدس الكسليك","Holy Spirit University of Kaslik","Lebanon",79],
  ["hong-kong-polytechnic-university","جامعة هونغ كونغ للفنون التطبيقية","Hong Kong Polytechnic University","Hong Kong",24],
  ["hong-kong-university-of-science-and-technology","جامعة هونغ كونغ للعلوم والتكنولوجيا","Hong Kong University of Science and Technology","Hong Kong",56],
  ["horseed-international-university","جامعة هورسيد الدولية","Horseed International University","Somalia",80],
  ["horus-university-in-egypt-hue","جامعة حوروس","Horus University in Egypt (HUE)","Egypt",81],
  ["idlib-university","جامعة ادلب","Idlib University","Syria",55],
  ["imam-abdulrahman-bin-faisal-university","جامعة الإمام عبدالرحمن بن فيصل","Imam Abdulrahman Bin Faisal University","Saudi Arabia",15],
  ["institut-polytechnique-de-paris","معهد البوليتكنيك في باريس","Institut Polytechnique de Paris","France",82],
  ["institut-teknologi-sepuluh-nopember-its-surabaya","معهد العاشر من نوفمبر للتكنولوجيا","Institut Teknologi Sepuluh Nopember (ITS Surabaya)","Indonesia",5],
  ["institute-of-management-technology-dubai","معهد تكنولوجيا الإدارة - دبي","Institute of Management Technology -Dubai","United Arab Emirates",1],
  ["international-university-for-science-and-technology","الجامعة الدولية الخاصة للعلوم والتكنولوجيا","International University for Science and Technology","Syria",9],
  ["islamic-university-of-lebanon-iul","الجامعة الإسلامية في لبنان","Islamic University of Lebanon (IUL)","Lebanon",83],
  ["islamic-university-of-madinah","الجامعة الإسلامية بالمدينة المنورة","Islamic University of Madinah","Saudi Arabia",15],
  ["istanbul-medeniyet-university","جامعة إسطنبول مدنيات","Istanbul Medeniyet University","Turkey",44],
  ["istanbul-technical-university","جامعة إسطنبول التقنية","Istanbul Technical University","Turkey",44],
  ["istanbul-university","جامعة إسطنبول","Istanbul University","Turkey",84],
  ["ittihad-private-university","جامعة الاتحاد الخاصة","Ittihad Private University","Syria",9],
  ["jadara-university","جامعة جدارا","Jadara University","Jordan",12],
  ["jazan-university","جامعة جازان","Jazan University","Saudi Arabia",15],
  ["jerash-university","جامعة جرش","Jerash University","Jordan",85],
  ["jinan-university","جامعة الجنان","Jinan University","Lebanon",86],
  ["jobkey-university","جامعة جوبكي","Jobkey University","Somalia",87],
  ["johns-hopkins-university","جامعة جونز هوبكنز","Johns Hopkins University","United States",2],
  ["jordan-university-of-science-and-technology","جامعة العلوم والتكنولوجيا الأردنية","Jordan University of Science and Technology","Jordan",88],
  ["kafrelsheikh-university","جامعة كفر الشيخ","Kafrelsheikh University","Egypt",18],
  ["karunya-institute-of-technology-and-sciences","معهد كارونيا للتكنولوجيا والعلوم","Karunya Institute of Technology and Sciences","India",89],
  ["kasem-bundit-university","جامعة قاسم بونديت","Kasem Bundit University","Thailand",1],
  ["kasetsart-university","جامعة كاسيتسارت","Kasetsart University","Thailand",1],
  ["kavayitri-bahinabai-chaudhari-north-maharashtra-university-jalgaon","جامعة شمال ماهاراشترا ، جالجاون","Kavayitri Bahinabai Chaudhari North Maharashtra University, Jalgaon","India",90],
  ["khalifa-university","جامعة خليفة","Khalifa University","United Arab Emirates",0],
  ["khon-kaen-university-international-college","كلية جامعة خون كاين الدولية","Khon Kaen University International College","Thailand",1],
  ["king-abdulaziz-university","جامعة الملك عبدالعزيز","King Abdulaziz University","Saudi Arabia",15],
  ["king-abdullah-university-of-science-and-technology","جامعة الملك عبد الله للعلوم والتقنية","King Abdullah University of Science and Technology","Saudi Arabia",37],
  ["king-fahd-university-of-petroleum-and-minerals","جامعة الملك فهد للبترول والمعادن","King Fahd University of Petroleum and Minerals","Saudi Arabia",10],
  ["king-faisal-university","جامعة الملك فيصل","King Faisal University","Saudi Arabia",10],
  ["king-khalid-university","جامعة الملك خالد","King Khalid University","Saudi Arabia",15],
  ["king-mongkuts-institute-of-technology-ladkrabang","معهد الملك راما الرابع للتكنولوجيا","King Mongkuts Institute of Technology Ladkrabang","Thailand",1],
  ["king-mongkuts-university-of-technology","جامعة الملك مونغكوت للتكنولوجيا","King Mongkut’s University of Technology","Thailand",1],
  ["king-saud-university","جامعة الملك سعود","King Saud University","Saudi Arabia",91],
  ["kingdom-university","جامعة المملكة","Kingdom University","Bahrain",3],
  ["knowledge-university","جامعة نولج","Knowledge University","Iraq",92],
  ["koc-university","جامعة كوتش","Koç University","Turkey",18],
  ["komar-university-of-science-and-technology","جامعة كومار للعلوم والتكنولوجيا","Komar University of Science and Technology","Iraq",0],
  ["koneru-lakshmaiah-deemed-to-be-university","جامعة كونيرو لاكشمايا","Koneru Lakshmaiah Deemed to be University","India",53],
  ["korea-advanced-institute-of-science-and-technology","المعهد الكوري المتقدم للعلوم والتكنولوجيا","Korea Advanced Institute of Science and Technology","South Korea",93],
  ["kuwait-college-of-science-and-technology","كلية الكويت للعلوم والتكنولوجيا","Kuwait College of Science and Technology","Kuwait",94],
  ["kuwait-university","جامعة الكويت","Kuwait University","Kuwait",3],
  ["lebanese-american-university","الجامعة اللبنانية الأمريكية","Lebanese American University","Lebanon",3],
  ["lebanese-german-university","الجامعة اللبنانية الألمانية","Lebanese German University","Lebanon",95],
  ["lebanese-international-university","الجامعة اللبنانية الدولية","Lebanese International University","Lebanon",96],
  ["lebanese-university-lu","الجامعة اللبنانية","Lebanese University (LU)","Lebanon",97],
  ["lusail-university","جامعة لوسيل","Lusail University","Qatar",1],
  ["mae-fah-luang-university","جامعة ماي فاه لوانغ","Mae Fah Luang University","Thailand",1],
  ["mahidol-university","جامعة ماهيدول","Mahidol University","Thailand",1],
  ["mahidol-university-international-college","جامعة ماهيدول الكلية الجامعية","Mahidol University International College","Thailand",1],
  ["majmaah-university","جامعة المجمعة","Majmaah University","Saudi Arabia",15],
  ["manara-university","جامعة المنارة","Manara University","Syria",9],
  ["mansoura-university","جامعة المنصورة","Mansoura University","Egypt",3],
  ["massachusetts-institute-of-technology-mit","معهد ماساتشوستس للتكنولوجيا","Massachusetts Institute of Technology (MIT)","United States",98],
  ["mazoon-college","كلية مزون","Mazoon College","Oman",99],
  ["mcgill-university","جامعة ماكجيل","McGill University","Canada",100],
  ["mcmaster-university","جامعة ماكماستر","McMaster University","Canada",101],
  ["mena-college-of-management","كلية مينا للإدارة","Mena College of Management","United Arab Emirates",0],
  ["menofia-university","جامعة المنوفية","Menofia University","Egypt",18],
  ["middle-east-college","كلية الشرق الأوسط","Middle East College","Oman",102],
  ["middle-east-technical-university","جامعة الشرق الأوسط التقنية","Middle East Technical University","Turkey",72],
  ["middle-east-university","جامعة الشرق الأوسط","Middle East University","Jordan",27],
  ["middle-georgia-state-university","جامعة ولاية جورجيا الوسطى","Middle Georgia State University","Georgia",26],
  ["minia-university","جامعة المنيا","Minia University","Egypt",0],
  ["misr-international-university","جامعة مصر الدولية","Misr International University","Egypt",0],
  ["misr-university-for-science-and-technology","جامعة مصر للعلوم والتكنولوجيا","Misr University for Science and Technology","Egypt",0],
  ["modern-sciences-and-arts-university","جامعة أكتوبر للعلوم الحديثة والآداب","Modern Sciences and Arts University","Egypt",3],
  ["modern-university-for-business-and-science","الجامعة الحديثة للإدارة والعلوم","Modern University for Business and Science","Lebanon",66],
  ["modern-university-for-technology-and-information","الجامعة الحديثة للتكنولوجيا والمعلومات","Modern University for Technology and Information","Egypt",103],
  ["mohammed-bin-rashid-school-of-government","كلية محمد بن راشد للإدارة الحكومية","Mohammed Bin Rashid School of Government","United Arab Emirates",0],
  ["mohammed-bin-rashid-university-of-medicine-and-health-sciences","جامعة محمد بن راشد للطب والعلوم الصحية","Mohammed Bin Rashid University of Medicine and Health Sciences","United Arab Emirates",0],
  ["monash-university","جامعة موناش","Monash University","Australia",104],
  ["montclair-state-university","جامعة ولاية مونتكلير","Montclair State University","United States",2],
  ["mutah-university","جامعة مؤتة","Mutah University","Jordan",105],
  ["nahda-university","جامعة النهضة","Nahda University","Egypt",18],
  ["najran-university","جامعة نجران","Najran University","Saudi Arabia",15],
  ["nanyang-technological-university-ntu","جامعة نانيانج التكنولوجية","Nanyang Technological University (NTU)","Singapore",106],
  ["naresuan-university","جامعة ناريسوان","Naresuan University","Thailand",1],
  ["national-taiwan-university","جامعة تايوان الوطنية","National Taiwan University","Taiwan",107],
  ["national-university-of-science-and-technology","الجامعة الوطنية للعلوم والتكنولوجيا","National University of Science and Technology","Oman",0],
  ["national-university-of-singapore-nus","جامعة سنغافورة الوطنية","National University of Singapore (NUS)","Singapore",106],
  ["new-mansoura-university","جامعة المنصورة الجديدة","New Mansoura University","Egypt",18],
  ["new-valley-university","جامعة الوادي الجديد","New Valley University","Egypt",108],
  ["new-york-institute-of-technology","معهد نيويورك للتكنولوجيا","New York Institute of Technology","United Arab Emirates",0],
  ["new-york-institute-of-technology-madaba","معهد نيويورك للتكنولوجيا، مادبا","New York Institute of Technology, Madaba","Jordan",0],
  ["new-york-university-abu-dhabi","جامعة نيويورك أبوظبي","New York University, Abu Dhabi","United Arab Emirates",0],
  ["new-york-university-nyu","جامعة نيويورك","New York University (NYU)","United States",109],
  ["nile-university","جامعة النيل","Nile University","Egypt",110],
  ["northern-technical-university","الجامعة التقنية الشمالية","Northern Technical University","Iraq",14],
  ["northwestern-university","جامعة نورث وسترن","Northwestern University","United States",111],
  ["northwestern-university-in-qatar","جامعة نورثويسترن في قطر","Northwestern University in Qatar","Qatar",40],
  ["notre-dame-university-louaize","جامعة السيدة اللويزة","Notre Dame University - Louaize","Lebanon",18],
  ["october-6-university","جامعة 6 أكتوبر","October 6 University","Egypt",0],
  ["ohio-university","جامعة أوهايو","Ohio University","United States",37],
  ["osaka-university","جامعة أوساكا","Osaka University","Japan",112],
  ["osmania-university","الجامعة العثمانية","Osmania University","India",113],
  ["pharos-university-in-alexandria","جامعة فاروس","Pharos University in Alexandria","Egypt",0],
  ["philadelphia-university","جامعة فيلادلفيا","Philadelphia University","Jordan",105],
  ["phoenicia-university","جامعة فينيسيا","Phoenicia University","Lebanon",19],
  ["president-university","جامعة بريزيدينت","President University","Indonesia",114],
  ["prince-mohammad-bin-fahd-university","جامعة الأمير محمد بن فهد","Prince Mohammad Bin Fahd University","Saudi Arabia",10],
  ["prince-sattam-bin-abdulaziz-university","جامعة الأمير سطام بن عبدالعزيز","Prince Sattam Bin Abdulaziz University","Saudi Arabia",15],
  ["prince-sultan-university","جامعة الأمير سلطان","Prince Sultan University","Saudi Arabia",10],
  ["princess-nourah-bint-abdulrahman-university","جامعة الأميرة نورة بنت عبدالرحمن","Princess Nourah bint Abdulrahman University","Saudi Arabia",15],
  ["princess-sumaya-university-for-technology-psut","جامعة الأميرة سمية للتكنولوجيا","Princess Sumaya University for Technology (PSUT)","Jordan",85],
  ["princeton-university","جامعة برينستون","Princeton University","United States",115],
  ["qassim-university","جامعة القصيم","Qassim University","Saudi Arabia",15],
  ["qatar-university","جامعة قطر","Qatar University","Qatar",1],
  ["queens-university","جامعة كوينز","Queens University","Canada",58],
  ["rabdan-academy","أكاديمية ربدان","Rabdan Academy","United Arab Emirates",0],
  ["rafik-hariri-university","جامعة رفيق الحريري","Rafik Hariri University","Lebanon",116],
  ["rak-medical-and-health-sciences-university","جامعة رأس الخيمة للطب والعلوم الصحية","RAK Medical and Health Sciences University","United Arab Emirates",117],
  ["ramkhamhaeng-university","جامعة رامخامهينج","Ramkhamhaeng University","Thailand",118],
  ["rice-university","جامعة رايس","Rice University","United States",119],
  ["royal-university-for-women","الجامعة الملكية للبنات","Royal University for Women","Bahrain",0],
  ["sabanci-university","جامعة صبنجة","Sabancı University","Turkey",0],
  ["sadat-academy-for-management-sciences","أكاديمية السادات للعلوم الإدارية","Sadat Academy for Management Sciences","Egypt",120],
  ["saint-george-university-of-beirut","جامعة القديس جاورجيوس في بيروت","Saint George University of Beirut","Lebanon",22],
  ["seoul-national-university","جامعة سيول الوطنية","Seoul National University","South Korea",121],
  ["shanghai-jiao-tong-university","جامعة شانغهاي جياو تونغ","Shanghai Jiao Tong University","China",56],
  ["shaqra-university","جامعة شقراء","Shaqra University","Saudi Arabia",15],
  ["sinai-university","جامعة سيناء","Sinai University","Egypt",18],
  ["singapore-institute-of-technology-sit","معهد سنغافورة للتكنولوجيا","Singapore Institute of Technology (SIT)","Singapore",122],
  ["singapore-management-university-smu","جامعة سنغافورة للإدارة","Singapore Management University (SMU)","Singapore",123],
  ["singapore-university-of-social-sciences-suss","جامعة سنغافورة للعلوم الاجتماعية","Singapore University of Social Sciences (SUSS)","Singapore",106],
  ["singapore-university-of-technology-and-design-sutd","جامعة سنغافورة للتكنولوجيا والتصميم","Singapore University of Technology and Design (SUTD)","Singapore",106],
  ["skyline-university-college","كلية الأفق الجامعية","Skyline University College","United Arab Emirates",1],
  ["sndt-womens-university","جامعة اس ان دي تي للنساء","SNDT Womens University","India",124],
  ["south-valley-university","جامعة جنوب الوادي","South Valley University","Egypt",125],
  ["sp-jain-school-of-global-management","مدرسة إس بي جين لإدارة الأعمال العالمية","SP Jain School of Global Management","United Arab Emirates",126],
  ["srinakharinwirot-university","جامعة سريناخارينويروت","Srinakharinwirot University","Thailand",1],
  ["srm-institute-of-science-and-technology","معهد إس آر إم للعلوم والتكنولوجيا","SRM Institute of Science and Technology","India",90],
  ["stanford-university","جامعة ستانفورد","Stanford University","United States",58],
  ["suez-canal-university","جامعة قناة السويس","Suez Canal University","Egypt",18],
  ["sukhothai-thammathirat-open-university","جامعة سوخوثاي ثماذيرات المفتوحة","Sukhothai Thammathirat Open University","Thailand",1],
  ["sultan-qaboos-university","جامعة السلطان قابوس","Sultan Qaboos University","Oman",0],
  ["sungkyunkwan-university","جامعة سونغ كيون كوان","Sungkyunkwan University","South Korea",55],
  ["sur-university-college","كلية صور الجامعية","Sur University College","Oman",1],
  ["suranaree-university-of-technology","جامعة سوراناري للتكنولوجيا","Suranaree University of Technology","Thailand",65],
  ["syrian-private-university","الجامعة السورية الخاصة","Syrian Private University","Syria",9],
  ["tafila-technical-university","جامعة الطفيلة التقنية","Tafila Technical University","Jordan",127],
  ["tanta-university","جامعة طنطا","Tanta University","Egypt",18],
  ["telkom-university","جامعة تلكوم","Telkom University","Indonesia",5],
  ["texas-a-and-m-university-at-qatar","جامعة تكساس إي أند أم في قطر","Texas A and M University at Qatar","Qatar",128],
  ["the-american-university-in-cairo","الجامعة الأمريكية بالقاهرة","The American University in Cairo","Egypt",0],
  ["the-arab-academy-for-management-banking-and-financial-sciences","الأكاديمية العربية للعلوم الإدارية والمالية والمصرفية","The Arab Academy for Management, Banking and Financial Sciences","Egypt",129],
  ["the-egyptian-chinese-university","الجامعة المصرية الصينية","The Egyptian Chinese University","Egypt",130],
  ["the-hashemite-university","الجامعة الهاشمية","The Hashemite University","Jordan",9],
  ["the-public-authority-for-applied-education-and-training","الهيئة العامة للتعليم التطبيقي والتدريب","The Public Authority for Applied Education and Training","Kuwait",3],
  ["the-university-of-alabama","جامعة ألاباما","The University of Alabama","United States",131],
  ["the-university-of-jordan","جامعة الأردن","The University of Jordan","Jordan",9],
  ["thompson-rivers-university","جامعة طومسون ريفرز","Thompson Rivers University","Canada",57],
  ["tikrit-university","جامعة تكريت","Tikrit University","Iraq",132],
  ["tishk-international-university","جامعة تيشك الدولية","Tishk International University","Iraq",72],
  ["tohoku-university","جامعة توهوكو","Tohoku University","Japan",133],
  ["tunis-business-school","مدرسة تونس للأعمال","Tunis Business School","Tunisia",0],
  ["united-arab-emirates-university","جامعة الإمارات العربية المتحدة","United Arab Emirates University","United Arab Emirates",0],
  ["universitas-andalas","جامعة الأندلس","Universitas Andalas","Indonesia",134],
  ["universitas-brawijaya","جامعة براويجايا","Universitas Brawijaya","Indonesia",46],
  ["universitas-hasanuddin","جامعة حسن الدين","Universitas Hasanuddin","Indonesia",134],
  ["universitas-indonesia","جامعة اندونيسيا","Universitas Indonesia","Indonesia",111],
  ["universitas-padjadjaran","جامعة بادجادجاران","Universitas Padjadjaran","Indonesia",135],
  ["universitas-sebelas-maret","جامعة سبلاس مارس","Universitas Sebelas Maret","Indonesia",26],
  ["universiti-brunei-darussalam","جامعة بروناي دار السلام","Universiti Brunei Darussalam","Brunei",136],
  ["universiti-islam-antarabangsa-malaysia","الجامعة الإسلامية العالمية في ماليزيا","Universiti Islam Antarabangsa Malaysia","Malaysia",137],
  ["universiti-kebangsaan-malaysia","الجامعة الوطنية في ماليزيا","Universiti Kebangsaan Malaysia","Malaysia",24],
  ["universiti-malaya","جامعة مالايا","Universiti Malaya","Malaysia",18],
  ["universiti-malaysia-kelantan","جامعة ماليزيا كلنتان","Universiti Malaysia Kelantan","Malaysia",115],
  ["universiti-malaysia-perlis","جامعة ماليزيا برليس","Universiti Malaysia Perlis","Malaysia",28],
  ["universiti-malaysia-sarawak","جامعة ماليزيا سراواك","Universiti Malaysia Sarawak","Malaysia",118],
  ["universiti-putra-malaysia","جامعة بوترا في ماليزيا","Universiti Putra Malaysia","Malaysia",138],
  ["universiti-sains-islam-malaysia","جامعة العلوم الإسلامية في ماليزيا","Universiti Sains Islam Malaysia","Malaysia",37],
  ["universiti-sains-malaysia","جامعة العلوم في ماليزيا","Universiti Sains Malaysia","Malaysia",37],
  ["universiti-sultan-zainal-abidin","جامعة السلطان زين العابدين","Universiti Sultan Zainal Abidin","Malaysia",3],
  ["universiti-taylors","جامعة تايلورز","Universiti Taylors","Malaysia",22],
  ["universiti-teknikal-malaysia-melaka","الجامعة التقنية الماليزية في ملقا","Universiti Teknikal Malaysia Melaka","Malaysia",139],
  ["universiti-teknologi-malaysia","جامعة التكنولوجيا في ماليزيا","Universiti Teknologi Malaysia","Malaysia",140],
  ["universiti-teknologi-mara","جامعة مارا للتكنولوجيا","Universiti Teknologi MARA","Malaysia",141],
  ["universiti-teknologi-petronas-utp","جامعة بتروناس للتكنولوجيا","Universiti Teknologi PETRONAS (UTP)","Malaysia",138],
  ["university-of-al-qadisiyah","جامعة القادسية","University of Al-Qadisiyah","Iraq",14],
  ["university-of-alberta","جامعة ألبيرتا","University of Alberta","Canada",18],
  ["university-of-anbar","جامعة الانبار","University of Anbar","Iraq",14],
  ["university-of-auckland","جامعة أوكلاند","University of Auckland","New Zealand",142],
  ["university-of-bahrain","جامعة البحرين","University of Bahrain","Bahrain",3],
  ["university-of-basrah","جامعة البصرة","University of Basrah","Iraq",14],
  ["university-of-birmingham","جامعة برمنغهام","University of Birmingham","United Kingdom",143],
  ["university-of-business-and-technology","جامعة الأعمال والتكنولوجيا","University of Business and Technology","Saudi Arabia",15],
  ["university-of-calgary","جامعة كالجاري","University of Calgary","Canada",18],
  ["university-of-calgry-in-qatar","جامعة كالجاري في قطر","University of Calgry in Qatar","Qatar",18],
  ["university-of-california-berkeley-ucb","جامعة كاليفورنيا","University of California - Berkeley (UCB)","United States",22],
  ["university-of-california-los-angeles-ucla","جامعة كاليفورنيا - لوس أنجلس","University of California - Los Angeles (UCLA)","United States",22],
  ["university-of-california-san-diego-ucsd","جامعة كاليفورنيا - سان دييغو","University of California - San Diego (UCSD)","United States",22],
  ["university-of-canterbury","جامعة كانتربري","University of Canterbury","New Zealand",144],
  ["university-of-chicago","جامعة شيكاغو","University of Chicago","United States",0],
  ["university-of-cincinnati","جامعة سينسيناتي","University of Cincinnati","United States",145],
  ["university-of-delhi","جامعة دلهي","University of Delhi","India",146],
  ["university-of-diyala","جامعة ديالى","University of Diyala","Iraq",14],
  ["university-of-doha-for-science-and-technology","جامعة الدوحة للعلوم والتكنولوجيا","University of Doha for Science and Technology","Qatar",1],
  ["university-of-dubai","جامعة دبي","University of Dubai","United Arab Emirates",138],
  ["university-of-fujairah","جامعة الفجيرة","University of Fujairah","United Arab Emirates",1],
  ["university-of-georgia","جامعة جورجيا","University of Georgia","Georgia",40],
  ["university-of-hargeisa","جامعة هرجيسا","University of Hargeisa","Somalia",147],
  ["university-of-hong-kong","جامعة هونغ كونغ","University of Hong Kong","Hong Kong",24],
  ["university-of-illinois-at-urbana-champaign","جامعة إلينوى","University of Illinois at Urbana - Champaign","United States",119],
  ["university-of-information-technology-and-communications-uoitc","جامعة تكنولوجيا المعلومات والاتصالات","University of Information Technology and Communications (UoITC)","Iraq",148],
  ["university-of-kalamoon","جامعة القلمون","University of Kalamoon","Syria",9],
  ["university-of-kansas","جامعة كانساس","University of Kansas","United States",2],
  ["university-of-kirkuk","جامعة كركوك","University of Kirkuk","Iraq",149],
  ["university-of-kufa","جامعة الكوفة","University of Kufa","Iraq",150],
  ["university-of-michigan-ann-arbor","جامعة ميتشيغان","University of Michigan-Ann Arbor","United States",151],
  ["university-of-misan","جامعة ميسان","University of Misan","Iraq",14],
  ["university-of-montreal","جامعة مونتريال","University of Montreal","Canada",152],
  ["university-of-mosul","جامعة الموصل","University of Mosul","Iraq",14],
  ["university-of-nizwa","جامعة نزوى","University of Nizwa","Oman",0],
  ["university-of-north-carolina-at-chapel-hill","جامعة ولاية كارولينا الشمالية في تشابل هيل","University of North Carolina at Chapel Hill","United States",0],
  ["university-of-north-texas","جامعة شمال تكساس","University of North Texas","United States",26],
  ["university-of-pennsylvania","جامعة بنسلفينيا","University of Pennsylvania","United States",18],
  ["university-of-petra","جامعة البترا","University of Petra","Jordan",37],
  ["university-of-science-and-technology-at-zewail-city","مدينة زويل للعلوم والتكنولوجيا","University of Science and Technology at Zewail City","Egypt",0],
  ["university-of-sciences-and-arts-in-lebanon","جامعة العلوم والآداب اللبنانية","University of Sciences and Arts in Lebanon","Lebanon",96],
  ["university-of-sharjah","جامعة الشارقة","University of Sharjah","United Arab Emirates",1],
  ["university-of-shatt-al-arab","جامعة شط العرب","University of Shatt Al-Arab","Iraq",14],
  ["university-of-technology-and-applied-sciences","جامعة التقنية والعلوم التطبيقية","University of Technology and Applied Sciences","Oman",40],
  ["university-of-technology-bahrain","جامعة البحرين للتكنولوجيا","University of Technology Bahrain","Bahrain",153],
  ["university-of-texas-at-austin","جامعة تكساس في أوستن","University of Texas at Austin","United States",37],
  ["university-of-the-sunshine-cost","جامعة صن شاين كوست","University of the Sunshine Cost","Australia",154],
  ["university-of-tokyo","جامعة طوكيو","University of Tokyo","Japan",155],
  ["university-of-toronto","جامعة تورنتو","University of Toronto","Canada",156],
  ["university-of-tripoli","جامعة طرابلس","University of Tripoli","Lebanon",0],
  ["university-of-tunis","جامعة تونس","University of Tunis","Tunisia",0],
  ["university-of-victoria","جامعة فكتوريا","University of Victoria","Canada",157],
  ["university-of-western-australia","جامعة أستراليا الغربية","University of Western Australia","Australia",158],
  ["university-of-wisconsin-madison","جامعة ويسكونسن - ماديسون","University of Wisconsin - Madison","United States",159],
  ["university-system-of-georgia","الجامعة النظامية في جورجيا","University System of Georgia","Georgia",0],
  ["vignans-foundation-for-science-technology-and-research","مؤسسة فيجناس للعلوم والتكنولوجيا والبحث","Vignans Foundation for Science, Technology and Research","India",160],
  ["virginia-commonwealth-university-in-qatar","جامعة فرجينيا كومنولث في قطر","Virginia Commonwealth University in Qatar","Qatar",26],
  ["weill-cornell-medical-college-in-qatar","كلية وايل كورنيل للطب في قطر","Weill Cornell Medical College in Qatar","Qatar",58],
  ["west-georgia-technical-college","كلية غرب جورجيا التقنية","West Georgia Technical College","Georgia",26],
  ["yale-university","جامعة ييل","Yale University","United States",77],
  ["yarmouk-university","جامعة اليرموك","Yarmouk University","Jordan",105],
  ["yonsei-university","جامعة يونسي","Yonsei University","South Korea",121],
  ["york-university","جامعة يورك","York University","Canada",161],
  ["zagazig-university","جامعة الزقازيق","Zagazig University","Egypt",0],
  ["zarqa-university","جامعة الزرقاء","Zarqa University","Jordan",17],
  ["zayed-university","جامعة زايد","Zayed University","United Arab Emirates",0],
  ["zewail-city-of-science-technology-and-innovation","مدينة زويل للعلوم والتكنولوجيا والإبتكار","Zewail City of Science, Technology and Innovation","Egypt",162],
];
