-- Round 2 (2026-09-25): rules read from the sources the admin submitted.
-- All rows land as `review` for the admin to approve.
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$naif-security$q$, $q$جامعة نايف العربية للعلوم الأمنية$q$, $q$SA$q$, $q$university$q$, null, $q$lectures$q$, 25, null, true, 50, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$دليل الطالب 1446هـ (2024-2025م)$q$, $q$[{"url": "https://nauss.edu.sa/ar/eservices/Documents/Student-Handbook%20(1).pdf", "title": "دليل الطالب 1446هـ - جامعة نايف العربية للعلوم الأمنية", "quote": "يحرم الطالب من دخول الاختبار النهائي إذا قلت نسبة حضوره عن (75%) من المحاضرات والدروس العملية المحددة لكل مقرر خلال الفصل الدراسي ... يجوز لمجلس عمادة القبول والتسجيل استثناءً رفع الحرمان ... على ألا تقل نسبة حضوره عن (50%) من المحاضرات والدروس العملية المحددة للمقرر."}]$q$::jsonb, $q$الجامعة تقدّم برامج دراسات عليا في الغالب (درجة النجاح في المقرر 70). مصدر رسمي قدّمته الأدمن.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$islamic-madinah$q$, $q$الجامعة الإسلامية بالمدينة المنورة$q$, $q$SA$q$, $q$university$q$, null, $q$lectures$q$, 25, null, true, 50, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$صفحة متطلبات التخرج - كلية الهندسة (تنقل حد مجلس الجامعة)$q$, $q$[{"url": "https://iu.edu.sa/faculty-of-engineering/students/graduation-requirements", "title": "الحضور والمواظبة - كلية الهندسة، الجامعة الإسلامية", "quote": "إذا قل حضور الطالب عن الحد الأدنى الذي حدده مجلس الجامعة (75 في المائة من المحاضرات والحصص والدروس المختبرية المخصصة لكل مقرر)، فسيُمنع الطالب من متابعة المقرر وسيتم رفض دخوله في الامتحان النهائي ... بشرط أن يقدم الطالب عذرًا مقبولًا للمجلس وأن تكون مشاركته الكلية أقل من 50٪."}, {"url": "photo:islamic-madinah/2026-09-25T10-15-28-528Z-1.png", "title": "لقطة الصفحة نفسها (رفعتها الأدمن)"}]$q$::jsonb, $q$الصفحة على موقع كلية الهندسة لكنها تنص على أن 75% هو الحد الذي حدده مجلس الجامعة. نص رفع الحرمان في الصفحة مترجم حرفيًا («أقل من 50٪»)؛ المقصود في اللائحة الموحدة: ألا يقل الحضور عن 50%.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$yamamah$q$, $q$جامعة اليمامة$q$, $q$SA$q$, $q$university$q$, null, $q$hours$q$, 20, null, true, null, $q$[]$q$::jsonb, $q$من يصل بعد بدء المحاضرة لا يُسمح له بالدخول ويُسجَّل غائبًا، ومن يخرج قبل نهايتها يُسجَّل غائبًا.$q$, $q${"limit_inclusive": true, "appeal": "قرار الحرمان نهائي وغير قابل للاعتراض (أُلغي بند الاعتراض في ديسمبر 2024)."}$q$::jsonb, $q$Policy on Attendance and DN, V 8.0 - effective 1 July 2026$q$, $q$[{"url": "https://yu.edu.sa/wp-content/uploads/2026/08/Policy-on-Attendance-and-DN-On-Campus-Online_V-8.0_01072026.pdf", "title": "Policy on Attendance and DN (On-Campus & Online) V8.0 - Al Yamamah University", "quote": "A student who accumulates absences amounting to twenty percent (20%) or more of the total scheduled contact hours for any course shall be ineligible to sit for the final examination in that course ... The determination of ineligibility for the final examination based on excessive absence shall be final and non-appealable."}]$q$::jsonb, $q$20% (ليست 25%) وتُحرم عند الوصول لـ20% نفسها لا بعد تجاوزها. لا يوجد رفع حرمان بعذر. إجابة الذكاء الاصطناعي المرفوعة كانت تقول 25% وهذا خطأ.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$dar-alhekma$q$, $q$جامعة دار الحكمة$q$, $q$SA$q$, $q$university$q$, null, $q$hours$q$, 25, null, true, null, $q$[10, 15]$q$::jsonb, $q$التأخر 5–10 دقائق يُعد تأخرًا، وأكثر من 10 دقائق يُعد غيابًا، وكل 3 تأخيرات = غياب واحد.$q$, $q${}$q$::jsonb, $q$Attendance policy page (no date stated)$q$, $q$[{"url": "https://www.dah.edu.sa/en/centers/E-learningCenter/Pages/Attendance-policy.aspx", "title": "Attendance Policy - Dar Al-Hekma University", "quote": "Students have an absence limit of 25% of course time; this includes excused and unexcused absences. Any absence exceeding 25% will warrant a DN (denial of entering the final exam). ... 3 late arrivals Equal 1 absence"}]$q$::jsonb, $q$الغياب بعذر وبدون عذر كلاهما يُحسب. الإنذارات عند 10% و15%. درجة DN تُحسب F في المعدل.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$almaarefa$q$, $q$جامعة المعرفة$q$, $q$SA$q$, $q$university$q$, null, $q$lectures$q$, 25, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$دليل الطالب (غير مؤرخ)$q$, $q$[{"url": "https://www.um.edu.sa/pdf/4-5%20UM%20student%20guide.pdf", "title": "دليل الطالب - جامعة المعرفة", "quote": "على الطالب المنتظم حضور المحاضرات والدروس العملية، ويحرم من دخول الاختبار النهائي فيها إذا قلت نسبة حضوره عن 75% من المحاضرات والدروس العملية أو الدروس السريرية ... في حال تعدي الطالب نسبة الحرمان 25% يتم النظر في الأعذار المقدمة من قبل القسم وعليه يتم القرار برفع الحرمان أو عدمه."}]$q$::jsonb, $q$الغياب يُحسب ضمن الـ25% سواء قُبل العذر أو لا؛ العذر يفيد فقط عند النظر في رفع الحرمان. العذر يُقدَّم خلال 5 أيام. (إجابة الذكاء الاصطناعي المرفوعة قالت إن الغياب بعذر لا يُحسب — وهذا يخالف الدليل).$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$dar-aluloom$q$, $q$جامعة دار العلوم$q$, $q$SA$q$, $q$university$q$, null, $q$lectures$q$, 25, null, true, 50, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$شعبان 1436هـ / يونيو 2015م (قبل لائحة 1444)$q$, $q$[{"url": "https://dau.edu.sa/dentistry/wp-content/uploads/sites/17/2023/03/DAU-Study-and-Examination-Bylaws-Ar.pdf", "title": "لائحة الدراسة والاختبارات للمرحلة الجامعية وقواعدها التنفيذية - جامعة دار العلوم (1436هـ)", "quote": "يحرم الطالب من دخول الاختبار النهائي إذا قلت نسبة حضوره عن (75%) من المحاضرات والدروس العملية المحددة لكل مقرر خلال الفصل الدراسي ... يعطى الطلبة المتغيبين 3 إنذارات تحذيرية بناء على نسبة غيابهم (هذه النسب تحدد من قبل مجلس الجامعة)"}]$q$::jsonb, $q$وثيقة قديمة (2015) — تأكد أنها ما زالت سارية. 3 إنذارات لكن نسبها غير مذكورة. العذر يُقدَّم خلال أسبوعين.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$kaust$q$, $q$جامعة الملك عبدالله للعلوم والتقنية$q$, $q$SA$q$, $q$university$q$, null, $q$unspecified$q$, null, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$Student Handbook 2026-2027$q$, $q$[{"url": "https://www.kaust.edu.sa/docs/kaustlibraries/documents/downloads/kaust_student-handbook_26_27.pdf?sfvrsn=582fb05f_8", "title": "KAUST Student Handbook 2026-2027", "quote": "(لا يوجد في الدليل حد غياب على مستوى الجامعة — بحثنا في كامل الدليل عن attendance/absence)"}]$q$::jsonb, $q$دراسات عليا فقط. لا حد غياب موحّد؛ يحدده أستاذ كل مقرر في الـ Syllabus. الطالب يشوف غيابه بدون نسبة.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$prince-fahd-sultan$q$, $q$جامعة الأمير فهد بن سلطان$q$, $q$SA$q$, $q$program$q$, $q$دكتور في الطب والجراحة (MD)$q$, $q$hours$q$, 25, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$تعليمات منح درجة البكالوريوس في الطب والجراحة (غير مؤرخة)$q$, $q$[{"url": "https://fbsu.edu.sa/PDF/Rules-Regulations-Arabic.pdf", "title": "تعليمات منح درجة البكالوريوس في تخصص دكتور في الطب والجراحة - جامعة فهد بن سلطان", "quote": "إذا غاب الطالب أكثر من 25% من مجموع الساعات المقررة للمساق بغض النظر عن سبب الغياب، يحرم من التقدم لجميع الامتحانات اللاحقة في ذلك المساق ويوضع له رمز (DN) ... ولعميد الكلية صلاحية تجاوز غياب ما نسبته (25%) ... بعذر قهري يقبل به على أن لا يتجاوز مجموع الغيابات (30%) بأي حال من الأحوال."}]$q$::jsonb, $q$خاص ببرنامج الطب فقط؛ لائحة بقية برامج الجامعة ما زالت ناقصة. DN يدخل في المعدل.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$effat$q$, $q$جامعة عفت$q$, $q$SA$q$, $q$program$q$, $q$البرامج المشتركة مع SOAS (دراسات عليا)$q$, $q$unspecified$q$, 20, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$REG-168-02 (2025)$q$, $q$[{"url": "https://www.soas.ac.uk/sites/default/files/2025-07/REG-168-02%20Effat%20University%20%26%20SOAS%20University%20of%20London%20Academic%20Regulations%20for%20Joint%20Taught%20Programmes.pdf", "title": "Effat University & SOAS Academic Regulations for Joint Taught Programmes", "quote": "The programmes governed by these regulations ... are subject to a minimum attendance requirement of 80% in order to pass the programme(s)."}]$q$::jsonb, $q$80% حضور شرط لاجتياز البرنامج (لا حرمان من مقرر). لا ينطبق على بكالوريوس عفت؛ لائحة البكالوريوس ما زالت ناقصة.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$prince-mugrin$q$, $q$جامعة الأمير مقرن بن عبدالعزيز$q$, $q$SA$q$, $q$program$q$, $q$برامج الدبلوم (مركز التعليم المستمر)$q$, $q$hours$q$, 25, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$شروط وأحكام منصة التعليم المستمر$q$, $q$[{"url": "https://elearning.upm.edu.sa/ar/pages/application-terms", "title": "الشروط والأحكام - مركز التعليم المستمر وخدمة المجتمع، جامعة الأمير مقرن", "quote": "منع الطالب من دخول الاختبار النهائي للمقرر نتيجة تجاوز نسبة الغياب المسموح بها والبالغة (25%) من الساعات المعتمدة للمقرر"}, {"url": "photo:prince-mugrin/2026-09-25T10-30-41-519Z-1.png", "title": "لقطة من الوثيقة (رفعتها الأدمن)"}]$q$::jsonb, $q$خاص بالدبلومات؛ لائحة البكالوريوس ما زالت ناقصة.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$ubt$q$, $q$جامعة الأعمال والتكنولوجيا$q$, $q$SA$q$, $q$program$q$, $q$منصة الدبلومات (مركز التدريب)$q$, $q$hours$q$, 25, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$الشروط والأحكام - منصة الدبلومات$q$, $q$[{"url": "https://diplomaplatform.ubt.edu.sa/pages/tos1", "title": "الشروط والأحكام - مركز التدريب بجامعة الأعمال والتكنولوجيا", "quote": "الحرمان ... الغياب المسموح بها والبالغة (25%) من الساعات المعتمدة للمقرر"}]$q$::jsonb, $q$خاص بمنصة الدبلومات؛ لائحة البكالوريوس ما زالت ناقصة.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
insert into public.attendance_policies (university_slug, university_name, country, scope, scope_name, method, max_absence, max_unexcused, excused_counts, excuse_floor_attendance, warnings, late_rule, details, effective, sources, note, status) values ($q$bahah$q$, $q$جامعة الباحة$q$, $q$SA$q$, $q$program$q$, $q$الدبلومات - كلية التعليم التطبيقي (BU-CEA)$q$, $q$lectures$q$, 25, null, true, null, $q$[]$q$::jsonb, null, $q${}$q$::jsonb, $q$الأسئلة الشائعة - BU-CEA$q$, $q$[{"url": "https://bucea.bu.edu.sa/pages/frequently-asked-questions", "title": "الأسئلة الشائعة - كلية التعليم التطبيقي بجامعة الباحة", "quote": "تُقبل الأعذار عن الغياب بما لا يتجاوز 25% من إجمالي المحاضرات، وتجاوز هذه النسبة يؤدي إلى حرمان المتدرب من استكمال البرنامج"}]$q$::jsonb, $q$خاص بدبلومات التعليم التطبيقي؛ لائحة البكالوريوس ما زالت ناقصة.$q$, $q$review$q$)
on conflict (university_slug, scope, coalesce(scope_name, '')) do update set university_name = excluded.university_name, country = excluded.country, method = excluded.method, max_absence = excluded.max_absence, max_unexcused = excluded.max_unexcused, excused_counts = excluded.excused_counts, excuse_floor_attendance = excluded.excuse_floor_attendance, warnings = excluded.warnings, late_rule = excluded.late_rule, details = excluded.details, effective = excluded.effective, sources = excluded.sources, note = excluded.note, updated_at = now()
  where public.attendance_policies.status <> 'verified';
update public.attendance_policies set method = 'hours', max_absence = 25, max_unexcused = 15, excused_counts = true, excuse_floor_attendance = null, late_rule = null, effective = $q$الإصدار الثالث، ذو القعدة 1446هـ (أبريل 2025م)$q$, sources = $q$[{"url": "https://www.iau.edu.sa/sites/default/files/resources/implementry_rules_for_the_undergraduate_study_and_examination_regulations.pdf", "title": "القواعد التنفيذية للائحة الدراسة والاختبارات للمرحلة الجامعية بجامعة الإمام عبدالرحمن بن فيصل - الإصدار الثالث (ذو القعدة 1446هـ / أبريل 2025م)", "quote": "على الطالب المنتظم حضور المحاضرات والدروس العملية ويُحرم من دخول الاختبارات النهائية لأي مقرر إذا زادت نسبة غيابه فيه على (15%) من ساعات الاتصال للمقرر خلال الفصل الدراسي ... يجوز لمجلس الكلية أو مَن يُفوّضه رفع الحرمان والسماح للطالب بدخول الاختبار النهائي، متى قدّم عذرًا مقبولًا -في نظام سجلات الطلاب- خلال أسبوع من تاريخ الغياب شريطة ألا تزيد نسبة غياب الطالب على (25%) من ساعات الاتصال للمقرر."}]$q$::jsonb, note = $q$15% بدون عذر، وبعذر مقبول (خلال أسبوع من الغياب) حتى 25% من ساعات الاتصال. يحدد مجلس الكلية الحد الأدنى للحضور في المقررات العملية. (المادتان 14 و15 وقواعدهما التنفيذية، ص16)$q$, details = '{}'::jsonb, status = 'review', updated_at = now() where university_slug = 'imam-abdulrahman' and scope = 'university';
update public.attendance_policies set note = coalesce(note, '') || $q$ | الرابط الذي قدّمته الأدمن (دليل الطالب 1438-1439هـ) يسبق لائحة 1444 وينص على 75% حضور؛ القاعدة المعتمدة هنا من القواعد التنفيذية 1444 (20%، و10% للسريري).$q$, updated_at = now() where university_slug = 'jazan' and scope = 'university';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: اللائحة التنفيذية 2025 — 15% بدون عذر / 25% بعذر (ساعات اتصال). حُدّثت القاعدة.$q$, done_at = now() where id = '939419b7-790c-493f-a18d-e37e516273e2';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: دليل الطالب 1438هـ — أقدم من لائحة 1444 المعتمدة (20%). أُضيفت ملاحظة.$q$, done_at = now() where id = '2c061cfa-0c0a-4585-bbf2-43c6cc563447';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: دليل الطالب 1446هـ — 75% حضور، رفع الحرمان حتى 50%.$q$, done_at = now() where id = '723b5c5a-9cf7-47e4-8efa-a1dfb67ac464';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: لقطة من صفحة الجامعة الرسمية — 75% حضور، رفع الحرمان حتى 50%.$q$, done_at = now() where id = '03a8945a-78e7-4463-9111-b2823eee8cfc';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: دليل 2026-27 بدون حد غياب موحّد (يحدده الأستاذ). الصورتان إجابة ذكاء اصطناعي ولم تُستخدما.$q$, done_at = now() where id = 'f88f73fe-930f-4769-9c2f-b50d488b43ad';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: لائحة البرامج المشتركة مع SOAS فقط (80% حضور). لائحة البكالوريوس ما زالت ناقصة.$q$, done_at = now() where id = '685b23a6-4204-4368-b2a6-82ce8ec070b1';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: تعليمات برنامج الطب فقط (25%، حتى 30% بعذر قهري). لائحة بقية البرامج ناقصة.$q$, done_at = now() where id = 'b5cec362-5eb7-4974-83da-04e596098f25';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: شروط منصة الدبلومات فقط (25% من الساعات). لائحة البكالوريوس ناقصة.$q$, done_at = now() where id = '6f3c75a1-06b6-4f19-80ea-abde8671b49d';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: لائحة 1436هـ (قديمة) — 75% حضور، 3 إنذارات.$q$, done_at = now() where id = '399fe7ef-b7a6-4192-a175-ad787720f86e';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: سياسة الحضور V8 (2026) — 20% أو أكثر = حرمان نهائي. الصورة (25%) كانت خطأ.$q$, done_at = now() where id = '5d75e0fd-ae93-4eb8-96c1-f73a74750632';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: صفحة سياسة الحضور — 25% (بعذر وبدون)، إنذارات 10% و15%، 3 تأخيرات = غياب.$q$, done_at = now() where id = '8851e3bc-261d-46a8-ba24-da6a6e2eb3a4';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: شروط منصة الدبلومات فقط (25%). لائحة البكالوريوس ناقصة.$q$, done_at = now() where id = '7a433fe1-892e-4aa5-88b6-81d69924c441';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: دليل الطالب — 25% والغياب بعذر يُحسب. الصورة كانت تقول عكس ذلك.$q$, done_at = now() where id = 'cfa70b14-123a-4f4d-87b0-dd2c596e5aee';
update public.attendance_policy_requests set status = 'done', result_note = $q$قُرئ: صفحة دبلومات كلية التعليم التطبيقي فقط (25%). لائحة البكالوريوس ناقصة.$q$, done_at = now() where id = '08af9054-a778-46e6-8ec7-0fe6f8ed4116';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الرابط لجامعة الأمير سطام (psau) وليس جامعة الأمير سلطان (psu)، والصورة إجابة ذكاء اصطناعي.$q$, done_at = now() where id = 'ef6b4e84-8c53-452a-bef9-250f3ebb87e2';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الموقع يمنع القراءة الآلية (403)، ولم نتأكد أنه موقع جامعة المستقبل بالقصيم. الصورة إجابة ذكاء اصطناعي.$q$, done_at = now() where id = 'b1111f96-0811-4057-8b42-d62d225ab961';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = '94ef1e33-0178-4ef4-9332-ff703b6e9692';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = '3f4e6e95-b239-428e-8b3f-ecd553d7bc82';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = 'ccc0fdf4-ace0-4d1f-b638-6bec6dc18033';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = 'e7feeddb-2f78-4684-9e92-af623d2df43c';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = '1a8a4c10-792a-4072-bc04-1b66de56ba38';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة لقطة من إجابة ذكاء اصطناعي وليست لائحة رسمية — لم تُستخدم. نحتاج رابط أو صورة من اللائحة نفسها.$q$, done_at = now() where id = '0c039f92-0e41-4132-891e-273e949eb8c1';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة إجابة ذكاء اصطناعي عن جامعة الإمام محمد بن سعود (جامعة أخرى) — لم تُستخدم. القاعدة أُخذت من اللائحة الرسمية 2025.$q$, done_at = now() where id = 'acef344d-8d36-48aa-8298-33259b089a61';
update public.attendance_policy_requests set status = 'failed', result_note = $q$الصورة إجابة ذكاء اصطناعي وتخالف لائحة جازان 1444 — لم تُستخدم.$q$, done_at = now() where id = '29f95919-813b-46b1-8d2e-67c86674ed3a';
